/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerCadastroGerente;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author iago2
 */
public class CadastroGerente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroGerente
     */
    public CadastroGerente() {
        initComponents();
        controller = new ControllerCadastroGerente(this);
    }

    public JButton getBtCadastrarGerente() {
        return btCadastrarGerente;
    }

    public void setBtCadastrarGerente(JButton btCadastrarGerente) {
        this.btCadastrarGerente = btCadastrarGerente;
    }

    public JLabel getLbCadastrarGerente() {
        return lbCadastrarGerente;
    }

    public void setLbCadastrarGerente(JLabel lbCadastrarGerente) {
        this.lbCadastrarGerente = lbCadastrarGerente;
    }

    public JLabel getLbLoginCadastroGerente() {
        return lbLoginCadastroGerente;
    }

    public void setLbLoginCadastroGerente(JLabel lbLoginCadastroGerente) {
        this.lbLoginCadastroGerente = lbLoginCadastroGerente;
    }

    public JLabel getLbNomeCadastroGerente() {
        return lbNomeCadastroGerente;
    }

    public void setLbNomeCadastroGerente(JLabel lbNomeCadastroGerente) {
        this.lbNomeCadastroGerente = lbNomeCadastroGerente;
    }

    public JLabel getLbSenhaCadastroGerente() {
        return lbSenhaCadastroGerente;
    }

    public void setLbSenhaCadastroGerente(JLabel lbSenhaCadastroGerente) {
        this.lbSenhaCadastroGerente = lbSenhaCadastroGerente;
    }

    public JTextField getTxtEntradaLoginCadastroGerente() {
        return txtEntradaLoginCadastroGerente;
    }

    public void setTxtEntradaLoginCadastroGerente(JTextField txtEntradaLoginCadastroGerente) {
        this.txtEntradaLoginCadastroGerente = txtEntradaLoginCadastroGerente;
    }

    public JTextField getTxtEntradaNomeCadastroGerente() {
        return txtEntradaNomeCadastroGerente;
    }

    public void setTxtEntradaNomeCadastroGerente(JTextField txtEntradaNomeCadastroGerente) {
        this.txtEntradaNomeCadastroGerente = txtEntradaNomeCadastroGerente;
    }

    public JTextField getTxtEntradaSenhaCadastroGerente() {
        return txtEntradaSenhaCadastroGerente;
    }

    public void setTxtEntradaSenhaCadastroGerente(JTextField txtEntradaSenhaCadastroGerente) {
        this.txtEntradaSenhaCadastroGerente = txtEntradaSenhaCadastroGerente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCadastrarGerente = new javax.swing.JLabel();
        txtEntradaSenhaCadastroGerente = new javax.swing.JTextField();
        txtEntradaLoginCadastroGerente = new javax.swing.JTextField();
        lbNomeCadastroGerente = new javax.swing.JLabel();
        lbLoginCadastroGerente = new javax.swing.JLabel();
        lbSenhaCadastroGerente = new javax.swing.JLabel();
        btCadastrarGerente = new javax.swing.JButton();
        txtEntradaNomeCadastroGerente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbCadastrarGerente.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbCadastrarGerente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCadastrarGerente.setText("Cadastrar Gerente");

        txtEntradaSenhaCadastroGerente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEntradaSenhaCadastroGerente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtEntradaLoginCadastroGerente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEntradaLoginCadastroGerente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbNomeCadastroGerente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNomeCadastroGerente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomeCadastroGerente.setText("Nome:");

        lbLoginCadastroGerente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLoginCadastroGerente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLoginCadastroGerente.setText("Login:");
        lbLoginCadastroGerente.setToolTipText("");

        lbSenhaCadastroGerente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSenhaCadastroGerente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSenhaCadastroGerente.setText("Senha:");

        btCadastrarGerente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastrarGerente.setText("Cadastrar");
        btCadastrarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarGerenteActionPerformed(evt);
            }
        });

        txtEntradaNomeCadastroGerente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEntradaNomeCadastroGerente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEntradaNomeCadastroGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaNomeCadastroGerenteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 3, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Banco Mariago");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCadastrarGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(287, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btCadastrarGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbLoginCadastroGerente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEntradaLoginCadastroGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSenhaCadastroGerente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEntradaSenhaCadastroGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNomeCadastroGerente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEntradaNomeCadastroGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(lbCadastrarGerente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEntradaNomeCadastroGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeCadastroGerente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEntradaLoginCadastroGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLoginCadastroGerente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEntradaSenhaCadastroGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSenhaCadastroGerente))
                .addGap(18, 18, 18)
                .addComponent(btCadastrarGerente)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntradaNomeCadastroGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaNomeCadastroGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaNomeCadastroGerenteActionPerformed

    private void btCadastrarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarGerenteActionPerformed
        // TODO add your handling code here:
        controller.salvarGerente();
    }//GEN-LAST:event_btCadastrarGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CadastroGerente().setVisible(true);
//            }
//        });
//    }

    // Instânciando controller.
    private ControllerCadastroGerente controller;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarGerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCadastrarGerente;
    private javax.swing.JLabel lbLoginCadastroGerente;
    private javax.swing.JLabel lbNomeCadastroGerente;
    private javax.swing.JLabel lbSenhaCadastroGerente;
    private javax.swing.JTextField txtEntradaLoginCadastroGerente;
    private javax.swing.JTextField txtEntradaNomeCadastroGerente;
    private javax.swing.JTextField txtEntradaSenhaCadastroGerente;
    // End of variables declaration//GEN-END:variables
}
