/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author iago2
 */
public class SenhaBanco extends javax.swing.JFrame {

    /**
     * Creates new form SenhaBanco
     */
    public SenhaBanco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSenhaBanco = new javax.swing.JLabel();
        txtEntradaSenhaBanco = new javax.swing.JTextField();
        lbSpoiler = new javax.swing.JLabel();
        btEntrarContaGerente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbSenhaBanco.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbSenhaBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSenhaBanco.setText("SenhaBanco");

        txtEntradaSenhaBanco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEntradaSenhaBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaSenhaBancoActionPerformed(evt);
            }
        });

        lbSpoiler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSpoiler.setText("Senha: 15072023");
        lbSpoiler.setToolTipText("");

        btEntrarContaGerente.setText("Entrar");
        btEntrarContaGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarContaGerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSenhaBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEntradaSenhaBanco)
                            .addComponent(lbSpoiler, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btEntrarContaGerente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lbSenhaBanco)
                .addGap(18, 18, 18)
                .addComponent(txtEntradaSenhaBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSpoiler)
                .addGap(18, 18, 18)
                .addComponent(btEntrarContaGerente)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntradaSenhaBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaSenhaBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaSenhaBancoActionPerformed

    private void btEntrarContaGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarContaGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEntrarContaGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SenhaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SenhaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SenhaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SenhaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SenhaBanco().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrarContaGerente;
    private javax.swing.JLabel lbSenhaBanco;
    private javax.swing.JLabel lbSpoiler;
    private javax.swing.JTextField txtEntradaSenhaBanco;
    // End of variables declaration//GEN-END:variables
}
